name: Publish Extension

on:
  push:
    tags:
      - v*

jobs:
  publish-extension:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: pnpm install

      - run: pnpm run typecheck:preview

      - name: Generate .vsix file
        run: pnpm run package

      - name: Publish Extension
        run: pnpm run publish -p $VSCE_PAT
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}
